Contour1:
  nrconts: 5
Cropping:
  bottom: 60
  left: 0
  right: 0
  top: 0
Erodil:
  dil_iters: 1
  ero_iters: 2
  kernel: 1
Paths:
  cwd: ./dst/2212_polycmut/54585312565441710210
  dstpath: ./dst/2302_pez
  srcpath: ./src/2302_pez
Processing1:
  movingaverage: 4
  threshold: 10
Thresholding:
  thrval: 20
