Cropping:
  bottom: 60
  left: 0
  right: 0
  top: 0
General:
  conversionstat: true
Hyperparameters:
  batch_size: 36
  epochs: 400
  layers: 0
  lr_adam: 0.034659233542555366
  neurons: 224
  optimizer: adam
Paths:
  dstpath: dst/2303_pez_dnn
  oldsrc: src/2302_pez_tfds
  srcpath: dst/2303_pez_dnn/traindat
