General:
  imagehight: 98
  imagewidth: 325
Hyperparameters:
  batch_size: 2
  dropout: false
  kernel_init: he_normal
  layers: 1
  lr_adam: 0.002010784540914254
  neurons: 1682
  optimizer: adam
Paths:
  srcpath: dst/2303_pez500
