General:
  imagehight: 98
  imagewidth: 325
Hyperparameters:
  batch_size: 1
  cnnlyrs: 3
  dropout: true
  initialfilternr: 16
  lr_adam: 0.0025885551978273836
  normalization: true
  optimizer: adam
Paths:
  srcpath: dst/2303_pez500
