Paths:
  dstpath: ./dst/2303_pez500
  labelsfname: labelsnew.csv
  srcpath: ./dst/2303_pez500
Processing:
  dil_iters: 46
  ero_iters: 24
  movinge_av: 20
  peakthr: 0
  smoothing_val: 6
  thrval: 104
