General:
  imagehight: 98
  imagewidth: 325
Hyperparameters:
  batch_size: 5
  cnnlyrs: 1
  dropout: true
  initialfilternr: 128
  lr_adam: 0.06002003765553237
  normalization: true
  optimizer: adam
Paths:
  srcpath: dst/2303_pez500
