Paths:
  dstpath: ./dst/2303_pez500
  labelsfname: labelsnew.csv
  srcpath: ./dst/2303_pez500
Processing:
  dil_iters: 30
  ero_iters: 3
  movinge_av: 3
  peakthr: 1
  smoothing_val: 13
  thrval: 251
