General:
  imagehight: 98
  imagewidth: 325
Hyperparameters:
  batch_size: 10
  dropout: false
  kernel_init: he_normal
  layers: 0
  lr_adam: 0.08547823928251153
  neurons: 128
  optimizer: adam
Paths:
  srcpath: dst/2303_pez500
