Hyperparameters:
  batch_size: 14
  cnnlyrs: 2
  dropout: false
  initialfilternr: 16
  layers: 5
  lr_adam: 0.03249234396367496
  neurons: 449
  normalization: true
  optimizer: adam
Paths:
  srcpath: dst/2303_pez500
