Cropping:
  bottom: 70
  left: 2
  right: 0
  top: 0
Erodil:
  dil_iters: 6
  ero_iters: 2
  kernel: 1
Paths:
  dstpath: ./dst/2303_pez500test
  srcpath: ./dst/2303_pez500
Processing1:
  movingaverage: 5
  threshold: 0
Thresholding:
  thrval: 44