General:
  imagehight: 98
  imagewidth: 325
Hyperparameters:
  batch_size: 2
  dropout: false
  kernel_init: he_normal
  layers: 0
  lr_adam: 0.0018538452677798545
  neurons: 32
  optimizer: adam
Paths:
  srcpath: dst/2303_pez500
