General:
  imagehight: 98
  imagewidth: 325
Hyperparameters:
  batch_size: 2
  dropout: true
  kernel_init: glorot_uniform
  layers: 1
  lr_adam: 0.09583026968059294
  neurons: 10187
  optimizer: adam
Paths:
  srcpath: dst/2303_pez500
