General:
  imagehight: 98
  imagewidth: 325
Hyperparameters:
  batch_size: 4
  cnnlyrs: 3
  dropout: false
  initialfilternr: 32
  layers: 3
  lr_adam: 0.01085060853570874
  normalization: true
  optimizer: adam
  pooling: true
Paths:
  srcpath: dst/2303_pez500
