General:
  imagehight: 98
  imagewidth: 325
Hyperparameters:
  batch_size: 280
  cnnlyrs: 3
  dropout: true
  initialfilternr: 16
  lr_adam: 0.052838547746831735
  normalization: false
  optimizer: adam
Paths:
  srcpath: dst/2303_pez500
