General:
  imagehight: 98
  imagewidth: 325
Hyperparameters:
  batch_size: 2
  cnnlyrs: 3
  dropout: false
  initialfilternr: 32
  lr_adam: 0.023351426888963262
  normalization: true
  optimizer: adam
  pooling: true
Paths:
  srcpath: dst/2303_pez500
