General:
  imagehight: 98
  imagewidth: 325
Hyperparameters:
  batch_size: 8
  dropout: false
  kernel_init: he_normal
  layers: 0
  lr_adam: 0.005104415823693265
  neurons: 0
  optimizer: adam
Paths:
  srcpath: dst/2303_pez500
