Cropping:
  bottom: 60
  left: 0
  right: 0
  top: 0
General:
  conversionstat: true
Hyperparameters:
  batch_size: 6
  epochs: 400
  layers: 6
  lr_adam: 0.0363082557285123
  neurons: 7417
  optimizer: adam
Paths:
  dstpath: dst/2303_pez_dnn
  oldsrc: src/2302_pez_tfds
  srcpath: dst/2303_pez_dnn/traindat
